[project]
name = "pysimpfun"
version = "0.2.1"
description = "Simpfun sdk by Python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "toml>=0.10.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pysimpfun", "pysimpfun.*"]